version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: domain-events
    environment:
      POSTGRES_DB: domain_events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

